### ISSUE TITLE
require_relative '../fizzbuzz.rb' has been removed from spec helper

### ISSUE THREAD

**Issue by amelieoller** [learn-co-students/rspec-fizzbuzz-v-000#1054]
The line `require_relative '../fizzbuzz.rb'` has been removed from the spec/spec_helper.rb which means that none of the tests are passing for students.

If you run into this simply add that line to your spec helper file.

@aviflombaum 
@DanielSeehausen

**Comment by DanielSeehausen** [comment]
Thank you @amelieoller ! Just updated with a push to master. Shouldn't have any issue with providing the correct solution and tests passing now (no need for the student to `require_relative` anymore).

**Comment by DanielSeehausen** [comment]
After reviewing further, adding in `require_relative` is an instruction in the readme.md
the line has been re-removed, and further instruction in both `fizzbuzz.rb` as well as the spec file has been added!

**Comment by amelieoller** [comment]
Gotcha. Sorry for the confusion, I hadn't seen the updates.
